version: "3.9"

services:
  
  anvil:
    build:
      context: ./anvil-base
      dockerfile: ./Dockerfile
      tags:
        - "cartesi/anvil:devel"
    command:
      [
        "anvil",
        "--host",
        "0.0.0.0",
        "--dump-state",
        "anvil_state.json"
      ]
    healthcheck:
      test: ["CMD", "eth_isready"]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - "8545:8545"
    volumes:
      - ./devnet/anvil_state:/anvil_state.json

  deploy-contracts:
    image: cartesi/rollups-hardhat:1.0.0
    environment:
      - RPC_URL=http://anvil:8545
    command:
      [
        "deploy",
        "--network",
        "localhost",
        "--export",
        "/opt/cartesi/share/deployments/localhost.json"
      ]
    init: true
    depends_on:
      anvil:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "test",
          "-f",
          "/opt/cartesi/share/deployments/localhost.json"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - ./devnet/deployments:/opt/cartesi/share/deployments
